(defpackage buffered-streams.test
  (:use #:cl #:parachute #:buffered-streams)
  (:import-from #:buffered-streams #:copy-cons)
  (:import-from
   #:alexandria
   #:copy-array
   #:read-stream-content-into-byte-vector
   #:read-stream-content-into-string))

(in-package #:buffered-streams.test)

(define-test suite)

(define-test buffered-streams::stream-ring-buffer :parent suite)

(define-test buffered-streams::stream-ring-buffer-read-element :parent buffered-streams::stream-ring-buffer
  (let ((buffer (buffered-streams::make-stream-ring-buffer
                 :stream (make-string-input-stream "12345678")
                 :buffer (make-array 4 :element-type 'character :initial-element #\Space))))
    (is char= #\1 (buffered-streams::stream-ring-buffer-read-element buffer))
    (is string= "12  " (buffered-streams::stream-ring-buffer-buffer buffer))
    (is char= #\2 (buffered-streams::stream-ring-buffer-read-element buffer))
    (is string= "12  " (buffered-streams::stream-ring-buffer-buffer buffer))
    (is char= #\3 (buffered-streams::stream-ring-buffer-read-element buffer))
    (is string= "1234" (buffered-streams::stream-ring-buffer-buffer buffer))
    (is char= #\4 (buffered-streams::stream-ring-buffer-read-element buffer))
    (is string= "1234" (buffered-streams::stream-ring-buffer-buffer buffer))
    (is char= #\5 (buffered-streams::stream-ring-buffer-read-element buffer))
    (is string= "5634" (buffered-streams::stream-ring-buffer-buffer buffer))
    (is char= #\6 (buffered-streams::stream-ring-buffer-read-element buffer))
    (is string= "5634" (buffered-streams::stream-ring-buffer-buffer buffer))
    (is char= #\7 (buffered-streams::stream-ring-buffer-read-element buffer))
    (is string= "5678" (buffered-streams::stream-ring-buffer-buffer buffer))
    (is char= #\8 (buffered-streams::stream-ring-buffer-read-element buffer))
    (is string= "5678" (buffered-streams::stream-ring-buffer-buffer buffer))
    (is eq :eof (buffered-streams::stream-ring-buffer-read-element buffer))
    (buffered-streams::stream-ring-buffer-seek buffer 4)
    (is string= "5678" (buffered-streams::stream-ring-buffer-buffer buffer))
    (is char= #\5 (buffered-streams::stream-ring-buffer-read-element buffer))
    (buffered-streams::stream-ring-buffer-seek buffer 3)
    (is string= "2345" (buffered-streams::stream-ring-buffer-buffer buffer))
    (is char= #\4 (buffered-streams::stream-ring-buffer-read-element buffer))
    (buffered-streams::stream-ring-buffer-seek buffer 2)
    (is string= "2345" (buffered-streams::stream-ring-buffer-buffer buffer))
    (is char= #\3 (buffered-streams::stream-ring-buffer-read-element buffer))
    (buffered-streams::stream-ring-buffer-seek buffer 0)
    (is string= "1234" (buffered-streams::stream-ring-buffer-buffer buffer))
    (is char= #\1 (buffered-streams::stream-ring-buffer-read-element buffer))
    (buffered-streams::stream-ring-buffer-seek buffer 4)
    (is string= "3456" (buffered-streams::stream-ring-buffer-buffer buffer))
    (is char= #\5 (buffered-streams::stream-ring-buffer-read-element buffer))))

(define-test+run buffered-streams::stream-ring-buffer-read-sequence :parent buffered-streams::stream-ring-buffer
  (let ((buffer (buffered-streams::make-stream-ring-buffer
                 :stream (make-string-input-stream "12345678")
                 :buffer (make-array 4 :element-type 'character :initial-element #\Space))))
    (let ((sequence (make-string 3 :initial-element #\Space)))
      (is = 3 (buffered-streams::stream-ring-buffer-read-sequence buffer sequence 0 3))
      (is string= "123" sequence)
      (is string= "1234" (buffered-streams::stream-ring-buffer-buffer buffer)))
    (let ((sequence (make-string 2 :initial-element #\Space)))
      (is = 2 (buffered-streams::stream-ring-buffer-read-sequence buffer sequence 0 2))
      (is string= "45" sequence)
      (is string= "5634" (buffered-streams::stream-ring-buffer-buffer buffer)))
    (buffered-streams::stream-ring-buffer-seek buffer 2)
    (let ((sequence (make-string 4 :initial-element #\Space)))
      (is = 4 (buffered-streams::stream-ring-buffer-read-sequence buffer sequence 0 4))
      (is string= "3456" sequence)
      (is string= "5634" (buffered-streams::stream-ring-buffer-buffer buffer)))
    (buffered-streams::stream-ring-buffer-seek buffer 7)
    (let ((sequence (make-string 3 :initial-element #\Space)))
      (is = 1 (buffered-streams::stream-ring-buffer-read-sequence buffer sequence 0 3))
      (is string= "8  " sequence)
      (is string= "6784" (buffered-streams::stream-ring-buffer-buffer buffer)))
    (let ((sequence (make-string 2 :initial-element #\Space)))
      (is = 0 (buffered-streams::stream-ring-buffer-read-sequence buffer sequence 0 2))
      (is string= "  " sequence)
      (is string= "6784" (buffered-streams::stream-ring-buffer-buffer buffer)))
    (buffered-streams::stream-ring-buffer-seek buffer 0)
    (let ((sequence (make-string 8 :initial-element #\Space)))
      (is = 8 (buffered-streams::stream-ring-buffer-read-sequence buffer sequence 0 8))
      (is string= "12345678" sequence)
      (is string= "5678" (buffered-streams::stream-ring-buffer-buffer buffer)))))

(define-test buffered-streams::buffered-input-stream :parent suite)

(define-test buffered-character-input-stream :parent buffered-streams::buffered-input-stream :depends-on (buffered-streams::stream-ring-buffer)
  (let* ((source "12345678")
         (stream (make-instance 'buffered-character-input-stream :stream (make-string-input-stream source) :size 4)))
    (is char= #\1 (read-char stream))
    (is char= #\2 (read-char stream))
    (is = 2 (file-position stream))
    (file-position stream 0)
    (is char= #\1 (read-char stream))
    (is char= #\2 (read-char stream))
    (is char= #\3 (read-char stream))
    (is char= #\4 (read-char stream))
    (is char= #\5 (read-char stream))
    (file-position stream 0)
    (is char= #\1 (read-char stream))
    (file-position stream 7)
    (is char= #\8 (read-char stream))
    (is eq :eof (read-char stream nil :eof))
    (file-position stream 0)
    (is string= source (read-stream-content-into-string stream))))

(define-test buffered-binary-input-stream :parent buffered-streams::buffered-input-stream :depends-on (buffered-streams::stream-ring-buffer)
  (let* ((source #(1 2 3 4 5 6 7 8))
         (stream (make-instance 'buffered-binary-input-stream :stream (flex:make-in-memory-input-stream source) :size 4)))
    (is = 1 (read-byte stream))
    (is = 2 (read-byte stream))
    (is = 2 (file-position stream))
    (file-position stream 0)
    (is = 1 (read-byte stream))
    (is = 2 (read-byte stream))
    (is = 3 (read-byte stream))
    (is = 4 (read-byte stream))
    (is = 5 (read-byte stream))
    (file-position stream 0)
    (is = 1 (read-byte stream))
    (file-position stream 7)
    (is = 8 (read-byte stream))
     (is eq :eof (read-byte stream nil :eof))
     (file-position stream 0)
     (is equalp source (read-stream-content-into-byte-vector stream))))

(define-test buffered-streams::character-index-buffer-compact :parent suite
  (let ((buffer (buffered-streams::make-character-index-buffer
                 :buffer (map 'vector #'copy-cons '((0 . 0) (8192 . 1) (12288 . 2) (14336 . 3) (15360 . 4) (16384 . 5)))
                 :interval 1024)))
    (buffered-streams::character-index-buffer-compact buffer)
    (is equalp #((0 . 0) (8192 . 1) (12288 . 2) (14336 . 3) (16384 . 5) (16384 . 5))
        (buffered-streams::character-index-buffer-buffer buffer)))
  (let ((buffer (buffered-streams::make-character-index-buffer
                 :buffer (map 'vector #'copy-cons '((0 . 0) (8192 . 1) (12288 . 2) (13312 . 3) (14336 . 4) (15360 . 5) (16384 . 6)))
                 :interval 1024)))
    (buffered-streams::character-index-buffer-compact buffer)
    (is equalp #((0 . 0) (8192 . 1) (12288 . 2) (14336 . 4) (15360 . 5) (16384 . 6) (16384 . 6))
        (buffered-streams::character-index-buffer-buffer buffer)))
  (let ((buffer (buffered-streams::make-character-index-buffer
                 :buffer (map 'vector #'copy-cons '((0 . 0) (1024 . 1) (2048 . 2) (3072 . 3) (4096 . 4)))
                 :interval 1024)))
    (buffered-streams::character-index-buffer-compact buffer)
    (is equalp #((0 . 0) (2048 . 2) (3072 . 3) (4096 . 4) (4096 . 4))
        (buffered-streams::character-index-buffer-buffer buffer)))
  (let ((buffer (buffered-streams::make-character-index-buffer
                 :buffer (map 'vector #'copy-cons '((0 . 0) (1024 . 1) (3072 . 2) (8192 . 3) (9216 . 4)))
                 :interval 1024)))
    (buffered-streams::character-index-buffer-compact buffer)
    (is equalp #((0 . 0) (3072 . 2) (8192 . 3) (9216 . 4) (9216 . 4))
        (buffered-streams::character-index-buffer-buffer buffer)))
  #+nil
  (let ((buffer (buffered-streams::make-character-index-buffer
                 :buffer (map 'vector #'copy-cons '((0 . 0) (32768 . 1) (49152 . 2) (57344 . 3) (61440 . 4) (63488 . 5) (64512 . 6)))
                 :interval 1024)))
    (buffered-streams::character-index-buffer-compact buffer)
    (is equalp #((0 . 0) (49152 . 2) (61440 . 4) (64512 . 6) (64512 . 6) (64512 . 6) (64512 . 6))
        (buffered-streams::character-index-buffer-buffer buffer))))

(define-test buffered-streams::character-index-buffer-update :parent suite
  (let* ((stream (make-instance 'character-indexed-input-stream :stream (make-string-input-stream "Hello World!") :interval 2 :size 4))
         (buffer (buffered-streams::stream-buffer stream)))
    (is char= #\H (read-char stream))
    (is equalp #((0 . 0) (1 . 1) (0 . 0) (0 . 0)) (buffered-streams::character-index-buffer-buffer buffer))
    (is char= #\e (read-char stream))
    (is equalp #((0 . 0) (2 . 2) (0 . 0) (0 . 0)) (buffered-streams::character-index-buffer-buffer buffer))
    (is char= #\l (read-char stream))
    (is equalp #((0 . 0) (2 . 2) (3 . 3) (0 . 0)) (buffered-streams::character-index-buffer-buffer buffer))
    (is char= #\l (read-char stream))
    (is equalp #((0 . 0) (2 . 2) (4 . 4) (0 . 0)) (buffered-streams::character-index-buffer-buffer buffer))
    (is char= #\o (read-char stream))
    (is equalp #((0 . 0) (2 . 2) (4 . 4) (5 . 5)) (buffered-streams::character-index-buffer-buffer buffer))
    (is char= #\Space (read-char stream))
    (is equalp #((0 . 0) (2 . 2) (4 . 4) (6 . 6)) (buffered-streams::character-index-buffer-buffer buffer))
    (is char= #\W (read-char stream))
    (is equalp #((0 . 0) (4 . 4) (6 . 6) (7 . 7)) (buffered-streams::character-index-buffer-buffer buffer))
    (is char= #\o (read-char stream))
    (is equalp #((0 . 0) (4 . 4) (6 . 6) (8 . 8)) (buffered-streams::character-index-buffer-buffer buffer))
    (is char= #\r (read-char stream))
    (is equalp #((0 . 0) (4 . 4) (8 . 8) (9 . 9)) (buffered-streams::character-index-buffer-buffer buffer))
    (file-position stream 5)
    (is equalp #((0 . 0) (4 . 4) (5 . 5) (0 . 0)) (buffered-streams::character-index-buffer-buffer buffer))
    (is char= #\Space (read-char stream))
    (is equalp #((0 . 0) (4 . 4) (6 . 6) (0 . 0)) (buffered-streams::character-index-buffer-buffer buffer))
    (is char= #\W (read-char stream))
    (is equalp #((0 . 0) (4 . 4) (6 . 6) (7 . 7)) (buffered-streams::character-index-buffer-buffer buffer))))

(define-test character-indexed-input-stream :parent suite
  (let ((source "aé你😀b"))
    (uiop:with-temporary-file (:stream temporary-stream :direction :io)
      (write-string source temporary-stream)
      (finish-output temporary-stream)
      (file-position temporary-stream 0)
      (let ((stream (make-instance 'character-indexed-input-stream :stream temporary-stream :interval 2 :size 3)))
        (is eq 'character (stream-element-type stream))
        (is char= #\a (read-char stream))
        (is = 1 (file-position stream))
        (is char= #\é (read-char stream))
        (is = 2 (file-position stream))
        (let ((sequence (make-string 2 :initial-element #\Space)))
          (is = 2 (read-sequence sequence stream))
          (is string= "你😀" sequence)
          (is = 4 (file-position stream)))
        (is = 1 (file-position stream 1))
        (is char= #\é (read-char stream))
        (is = 2 (file-position stream))
        (unread-char #\é stream)
        (is = 1 (file-position stream))
        (is char= #\é (read-char stream))
        (is = 4 (file-position stream 4))
        (is char= #\b (read-char stream))
        (is eq :eof (read-char stream nil :eof))
        (is = 0 (file-position stream 0))
        (is string= source (read-stream-content-into-string stream))))))
