(defpackage buffered-streams.test
  (:use #:cl #:parachute #:buffered-streams)
  (:import-from
   #:alexandria
   #:read-stream-content-into-byte-vector
   #:read-stream-content-into-string))

(in-package #:buffered-streams.test)

(define-test suite)

(define-test buffered-streams::stream-ring-buffer :parent suite)

(define-test buffered-streams::stream-ring-buffer-read-element :parent buffered-streams::stream-ring-buffer
  (let ((buffer (buffered-streams::make-stream-ring-buffer
                 :stream (make-string-input-stream "12345678")
                 :buffer (make-array 4 :element-type 'character :initial-element #\Space))))
    (is char= #\1 (buffered-streams::stream-ring-buffer-read-element buffer))
    (is string= "12  " (buffered-streams::stream-ring-buffer-buffer buffer))
    (is char= #\2 (buffered-streams::stream-ring-buffer-read-element buffer))
    (is string= "12  " (buffered-streams::stream-ring-buffer-buffer buffer))
    (is char= #\3 (buffered-streams::stream-ring-buffer-read-element buffer))
    (is string= "1234" (buffered-streams::stream-ring-buffer-buffer buffer))
    (is char= #\4 (buffered-streams::stream-ring-buffer-read-element buffer))
    (is string= "1234" (buffered-streams::stream-ring-buffer-buffer buffer))
    (is char= #\5 (buffered-streams::stream-ring-buffer-read-element buffer))
    (is string= "5634" (buffered-streams::stream-ring-buffer-buffer buffer))
    (is char= #\6 (buffered-streams::stream-ring-buffer-read-element buffer))
    (is string= "5634" (buffered-streams::stream-ring-buffer-buffer buffer))
    (is char= #\7 (buffered-streams::stream-ring-buffer-read-element buffer))
    (is string= "5678" (buffered-streams::stream-ring-buffer-buffer buffer))
    (is char= #\8 (buffered-streams::stream-ring-buffer-read-element buffer))
    (is string= "5678" (buffered-streams::stream-ring-buffer-buffer buffer))
    (is eq :eof (buffered-streams::stream-ring-buffer-read-element buffer))
    (buffered-streams::stream-ring-buffer-seek buffer 4)
    (is string= "5678" (buffered-streams::stream-ring-buffer-buffer buffer))
    (is char= #\5 (buffered-streams::stream-ring-buffer-read-element buffer))
    (buffered-streams::stream-ring-buffer-seek buffer 3)
    (is string= "2345" (buffered-streams::stream-ring-buffer-buffer buffer))
    (is char= #\4 (buffered-streams::stream-ring-buffer-read-element buffer))
    (buffered-streams::stream-ring-buffer-seek buffer 2)
    (is string= "2345" (buffered-streams::stream-ring-buffer-buffer buffer))
    (is char= #\3 (buffered-streams::stream-ring-buffer-read-element buffer))
    (buffered-streams::stream-ring-buffer-seek buffer 0)
    (is string= "1234" (buffered-streams::stream-ring-buffer-buffer buffer))
    (is char= #\1 (buffered-streams::stream-ring-buffer-read-element buffer))
    (buffered-streams::stream-ring-buffer-seek buffer 4)
    (is string= "3456" (buffered-streams::stream-ring-buffer-buffer buffer))
    (is char= #\5 (buffered-streams::stream-ring-buffer-read-element buffer))))

(define-test+run buffered-streams::stream-ring-buffer-read-sequence :parent buffered-streams::stream-ring-buffer
  (let ((buffer (buffered-streams::make-stream-ring-buffer
                 :stream (make-string-input-stream "12345678")
                 :buffer (make-array 4 :element-type 'character :initial-element #\Space))))
    (let ((sequence (make-string 3 :initial-element #\Space)))
      (is = 3 (buffered-streams::stream-ring-buffer-read-sequence buffer sequence 0 3))
      (is string= "123" sequence)
      (is string= "1234" (buffered-streams::stream-ring-buffer-buffer buffer)))
    (let ((sequence (make-string 2 :initial-element #\Space)))
      (is = 2 (buffered-streams::stream-ring-buffer-read-sequence buffer sequence 0 2))
      (is string= "45" sequence)
      (is string= "5634" (buffered-streams::stream-ring-buffer-buffer buffer)))
    (buffered-streams::stream-ring-buffer-seek buffer 2)
    (let ((sequence (make-string 4 :initial-element #\Space)))
      (is = 4 (buffered-streams::stream-ring-buffer-read-sequence buffer sequence 0 4))
      (is string= "3456" sequence)
      (is string= "5634" (buffered-streams::stream-ring-buffer-buffer buffer)))
    (buffered-streams::stream-ring-buffer-seek buffer 7)
    (let ((sequence (make-string 3 :initial-element #\Space)))
      (is = 1 (buffered-streams::stream-ring-buffer-read-sequence buffer sequence 0 3))
      (is string= "8  " sequence)
      (is string= "6784" (buffered-streams::stream-ring-buffer-buffer buffer)))
    (let ((sequence (make-string 2 :initial-element #\Space)))
      (is = 0 (buffered-streams::stream-ring-buffer-read-sequence buffer sequence 0 2))
      (is string= "  " sequence)
      (is string= "6784" (buffered-streams::stream-ring-buffer-buffer buffer)))
    (buffered-streams::stream-ring-buffer-seek buffer 0)
    (let ((sequence (make-string 8 :initial-element #\Space)))
      (is = 8 (buffered-streams::stream-ring-buffer-read-sequence buffer sequence 0 8))
      (is string= "12345678" sequence)
      (is string= "5678" (buffered-streams::stream-ring-buffer-buffer buffer)))))

(define-test buffered-streams::buffered-input-stream :parent suite)

(define-test buffered-character-input-stream :parent buffered-streams::buffered-input-stream :depends-on (buffered-streams::stream-ring-buffer)
  (let* ((source "12345678")
         (stream (make-instance 'buffered-character-input-stream :stream (make-string-input-stream source) :size 4)))
    (is char= #\1 (read-char stream))
    (is char= #\2 (read-char stream))
    (is = 2 (file-position stream))
    (file-position stream 0)
    (is char= #\1 (read-char stream))
    (is char= #\2 (read-char stream))
    (is char= #\3 (read-char stream))
    (is char= #\4 (read-char stream))
    (is char= #\5 (read-char stream))
    (file-position stream 0)
    (is char= #\1 (read-char stream))
    (file-position stream 7)
    (is char= #\8 (read-char stream))
    (is eq :eof (read-char stream nil :eof))
    (file-position stream 0)
    (is string= source (read-stream-content-into-string stream))))

(define-test buffered-binary-input-stream :parent buffered-streams::buffered-input-stream :depends-on (buffered-streams::stream-ring-buffer)
  (let* ((source #(1 2 3 4 5 6 7 8))
         (stream (make-instance 'buffered-binary-input-stream :stream (flex:make-in-memory-input-stream source) :size 4)))
    (is = 1 (read-byte stream))
    (is = 2 (read-byte stream))
    (is = 2 (file-position stream))
    (file-position stream 0)
    (is = 1 (read-byte stream))
    (is = 2 (read-byte stream))
    (is = 3 (read-byte stream))
    (is = 4 (read-byte stream))
    (is = 5 (read-byte stream))
    (file-position stream 0)
    (is = 1 (read-byte stream))
    (file-position stream 7)
    (is = 8 (read-byte stream))
    (is eq :eof (read-byte stream nil :eof))
    (file-position stream 0)
    (is equalp source (read-stream-content-into-byte-vector stream))))
