(defpackage buffered-streams.test
  (:use #:cl #:parachute #:buffered-streams)
  (:import-from
   #:alexandria
   #:read-stream-content-into-byte-vector
   #:read-stream-content-into-string))

(in-package #:buffered-streams.test)

(define-test suite)

(define-test buffered-streams::stream-ring-buffer :parent suite
  (let ((buffer (buffered-streams::make-stream-ring-buffer
                 :stream (make-string-input-stream "12345678")
                 :buffer (make-array 4 :element-type 'character :initial-element #\Space))))
    (is char= #\1 (buffered-streams::stream-ring-buffer-read-one buffer))
    (is string= "12  " (buffered-streams::stream-ring-buffer-buffer buffer))
    (is char= #\2 (buffered-streams::stream-ring-buffer-read-one buffer))
    (is string= "12  " (buffered-streams::stream-ring-buffer-buffer buffer))
    (is char= #\3 (buffered-streams::stream-ring-buffer-read-one buffer))
    (is string= "1234" (buffered-streams::stream-ring-buffer-buffer buffer))
    (is char= #\4 (buffered-streams::stream-ring-buffer-read-one buffer))
    (is string= "1234" (buffered-streams::stream-ring-buffer-buffer buffer))
    (is char= #\5 (buffered-streams::stream-ring-buffer-read-one buffer))
    (is string= "5634" (buffered-streams::stream-ring-buffer-buffer buffer))
    (is char= #\6 (buffered-streams::stream-ring-buffer-read-one buffer))
    (is string= "5634" (buffered-streams::stream-ring-buffer-buffer buffer))
    (is char= #\7 (buffered-streams::stream-ring-buffer-read-one buffer))
    (is string= "5678" (buffered-streams::stream-ring-buffer-buffer buffer))
    (is char= #\8 (buffered-streams::stream-ring-buffer-read-one buffer))
    (is string= "5678" (buffered-streams::stream-ring-buffer-buffer buffer))
    (is eq :eof (buffered-streams::stream-ring-buffer-read-one buffer))
    (buffered-streams::stream-ring-buffer-seek buffer 4)
    (is string= "5678" (buffered-streams::stream-ring-buffer-buffer buffer))
    (is char= #\5 (buffered-streams::stream-ring-buffer-read-one buffer))
    (buffered-streams::stream-ring-buffer-seek buffer 3)
    (is string= "2345" (buffered-streams::stream-ring-buffer-buffer buffer))
    (is char= #\4 (buffered-streams::stream-ring-buffer-read-one buffer))
    (buffered-streams::stream-ring-buffer-seek buffer 2)
    (is string= "2345" (buffered-streams::stream-ring-buffer-buffer buffer))
    (is char= #\3 (buffered-streams::stream-ring-buffer-read-one buffer))
    (buffered-streams::stream-ring-buffer-seek buffer 0)
    (is string= "1234" (buffered-streams::stream-ring-buffer-buffer buffer))
    (is char= #\1 (buffered-streams::stream-ring-buffer-read-one buffer))
    (buffered-streams::stream-ring-buffer-seek buffer 4)
    (is string= "3456" (buffered-streams::stream-ring-buffer-buffer buffer))
    (is char= #\5 (buffered-streams::stream-ring-buffer-read-one buffer))))

(define-test buffered-character-input-stream :parent suite :depends-on (buffered-streams::stream-ring-buffer)
  (let* ((source "12345678")
         (stream (make-instance 'buffered-character-input-stream :stream (make-string-input-stream source) :size 4)))
    (is char= #\1 (read-char stream))
    (is char= #\2 (read-char stream))
    (is = 2 (file-position stream))
    (file-position stream 0)
    (is char= #\1 (read-char stream))
    (is char= #\2 (read-char stream))
    (is char= #\3 (read-char stream))
    (is char= #\4 (read-char stream))
    (is char= #\5 (read-char stream))
    (file-position stream 0)
    (is char= #\1 (read-char stream))
    (file-position stream 7)
    (is char= #\8 (read-char stream))
    (is eq :eof (read-char stream nil :eof))
    (file-position stream 0)
    (is string= source (read-stream-content-into-string stream))))

(define-test buffered-binary-input-stream :parent suite :depends-on (buffered-streams::stream-ring-buffer)
  (let* ((source #(1 2 3 4 5 6 7 8))
         (stream (make-instance 'buffered-binary-input-stream :stream (flex:make-in-memory-input-stream source) :size 4)))
    (is = 1 (read-byte stream))
    (is = 2 (read-byte stream))
    (is = 2 (file-position stream))
    (file-position stream 0)
    (is = 1 (read-byte stream))
    (is = 2 (read-byte stream))
    (is = 3 (read-byte stream))
    (is = 4 (read-byte stream))
    (is = 5 (read-byte stream))
    (file-position stream 0)
    (is = 1 (read-byte stream))
    (file-position stream 7)
    (is = 8 (read-byte stream))
    (is eq :eof (read-byte stream nil :eof))
    (file-position stream 0)
    (is equalp source (read-stream-content-into-byte-vector stream))))
